name: ci
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

permissions:
  contents: read

jobs:
  plugin-ci:
    uses: mattermost/actions-workflows/.github/workflows/plugin-ci.yml@main
    secrets: inherit
